### PR TITLE
fix issues/1463 : Make default JUL-based logging asynchronous

### LINKED ISSUE #1463: Make default JUL-based logging asynchronous
Reactor blockhound detected blocking calls where RecordLog flushes logs with sync IO.

weblux（spring cloud gateway）下应该避免同步IO处理的

```java
reactor.blockhound.BlockingOperationError: Blocking call! java.io.FileOutputStream#writeBytes
	at java.io.FileOutputStream.writeBytes(FileOutputStream.java)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP POST "/hello/yyy?token=sadasdas" [ExceptionHandlingWebHandler]
Stack trace:
		at java.io.FileOutputStream.writeBytes(FileOutputStream.java)
		at java.io.FileOutputStream.write(FileOutputStream.java:326)
		at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
		at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
		at java.io.PrintStream.write(PrintStream.java:482)
		at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
		at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
		at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
		at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185)
		at java.io.PrintStream.write(PrintStream.java:527)
		at java.io.PrintStream.print(PrintStream.java:669)
		at java.io.PrintStream.println(PrintStream.java:806)
		at com.alibaba.csp.sentinel.log.LogBase.<clinit>(LogBase.java:72)
		at com.alibaba.csp.sentinel.adapter.gateway.common.rule.GatewayRuleManager$GatewayRulePropertyListener.applyToConvertedParamMap(GatewayRuleManager.java:214)
		at com.alibaba.csp.sentinel.adapter.gateway.common.rule.GatewayRuleManager$GatewayRulePropertyListener.applyGatewayRuleInternal(GatewayRuleManager.java:148)
		at com.alibaba.csp.sentinel.adapter.gateway.common.rule.GatewayRuleManager$GatewayRulePropertyListener.configLoad(GatewayRuleManager.java:124)
		at com.alibaba.csp.sentinel.adapter.gateway.common.rule.GatewayRuleManager$GatewayRulePropertyListener.configLoad(GatewayRuleManager.java:114)
		at com.alibaba.csp.sentinel.property.DynamicSentinelProperty.addListener(DynamicSentinelProperty.java:40)
		at com.alibaba.csp.sentinel.adapter.gateway.common.rule.GatewayRuleManager.<clinit>(GatewayRuleManager.java:57)
		at com.alibaba.csp.sentinel.adapter.gateway.common.param.GatewayParamParser.parseParameterFor(GatewayParamParser.java:58)
		at cn.sunline.edsp.gateway.server.filters.SentinelGatewayFilter.filter(SentinelGatewayFilter.java:71)
		at org.springframework.cloud.gateway.handler.FilteringWebHandler$GatewayFilterAdapter.filter(FilteringWebHandler.java:138)
		at org.springframework.cloud.gateway.filter.OrderedGatewayFilter.filter(OrderedGatewayFilter.java:44)
		at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.lambda$filter$0(FilteringWebHandler.java:118)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:153)
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
		at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:287)
		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:330)
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1712)
		at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:160)
		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
		at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:421)
		at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:211)
		at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:369)
		at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:367)
		at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:489)
		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:90)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:214)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.lang.Thread.run(Thread.java:748)

```

### PR DESCRIPTION
**Pull request by karl-sy**
### Describe what this PR does / why we need it
Make default JUL-based logging asynchronous

### Does this pull request fix one issue?
Fixes #1463

### Describe how you did it
use java.util.concurrent.Executor, submit the log task into single thread.

### CODE REVIEW

**Comment by karl-sy** [comment]
add asynchronous test cases

**Comment by karl-sy** [comment]
add asynchronous test cases

File: sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/ConsoleHandler.java [hunk 1]
```diff
@@ -42,6 +47,9 @@ class ConsoleHandler extends Handler {
      * A Handler which publishes log records to System.err.
      */
     private StreamHandler stderrHandler;
+    @SuppressWarnings("PMD.ThreadPoolCreationRule")
```
Comment (sczyh30) [inline sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/ConsoleHandler.java:50]: You have to follow the Java code guidelines rather than skip it with `@SuppressWarnings`. The queue should be bounded.

File: sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/ConsoleHandler.java [hunk 2]
```diff
@@ -42,6 +47,9 @@ class ConsoleHandler extends Handler {
...
+    private final ExecutorService executor = Executors.newSingleThreadExecutor(
+            new NamedThreadFactory("sentinel-log-executor", true));
```
Comment (sczyh30) [inline sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/ConsoleHandler.java:52]: You may need to refine the thread name so that we could distinguish the actual type of the logging (e.g. to file or to console).

File: sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/ConsoleHandler.java [hunk 3]
```diff
@@ -79,6 +89,12 @@ public void flush() {
 
     @Override
     public void close() throws SecurityException {
+        executor.shutdown();
+        try {
+            executor.awaitTermination(3, TimeUnit.SECONDS);
```
Comment (sczyh30) [inline sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/ConsoleHandler.java:94]: Should we block and wait for termination here?

**Review by sczyh30 — CHANGES_REQUESTED** [review]

File: sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/ConsoleHandler.java (hunk 1 above)
Comment (karl-sy) [reply sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/ConsoleHandler.java]: has deleted

File: sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/DateFileLogHandler.java [hunk 4]
```diff
@@ -34,6 +39,10 @@ public SimpleDateFormat initialValue() {
         }
     };
 
+    @SuppressWarnings("PMD.ThreadPoolCreationRule")
```
[the remark this answers is not in the document]
Comment (karl-sy) [reply sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/DateFileLogHandler.java]: has deleted

File: sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/ConsoleHandler.java (hunk 2 above)
Comment (karl-sy) [reply sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/ConsoleHandler.java]: has renamed

File: sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/ConsoleHandler.java (hunk 3 above)
Comment (karl-sy) [reply sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/ConsoleHandler.java]: has deleted

File: sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/ConsoleHandler.java [hunk 5]
```diff
@@ -43,9 +50,21 @@ class ConsoleHandler extends Handler {
...
     public ConsoleHandler() {
         this.stdoutHandler = new StreamHandler(System.out, new CspFormatter());
         this.stderrHandler = new StreamHandler(System.err, new CspFormatter());
+
+        int corePoolSize = 1;
+        int maximumPoolSize = 1;
+        long keepAliveTime = 0;
+        /**insure the log can be recorded*/
+        int queueSize = 1024;
+        RejectedExecutionHandler handler = new ThreadPoolExecutor.DiscardPolicy();
```
Comment (LearningGp) [inline sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/ConsoleHandler.java:64]: DiscardPolicy may prevent us from knowing if any logs were discarded, which can be misleading when troubleshooting. FYR, using the AbortPolicy and adding exception handling may be a way to avoid this kind of misleading.

File: sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/DateFileLogHandler.java [hunk 6]
```diff
@@ -55,10 +64,22 @@ public SimpleDateFormat initialValue() {
         this.append = append;
         rotateDate();
         this.initialized = true;
+
+        int corePoolSize = 1;
+        int maximumPoolSize = 1;
+        long keepAliveTime = 0;
+        /**insure the log can be recorded*/
+        int queueSize = 1024;
+        RejectedExecutionHandler handler = new ThreadPoolExecutor.DiscardPolicy();
```
Comment (LearningGp) [inline sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/DateFileLogHandler.java:73]: Ditto.

File: sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/ConsoleHandler.java (hunk 5 above)
Comment (karl-sy) [reply sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/ConsoleHandler.java]: defined RejectedExecutionHandler to record the rejected log task
1.AbortPolicy would stop record tasks, may be not the better choice
2.another problem is that it's not easy to record the message when log task is rejected due to the task itself is to log something, so just prints the rejected record

Comment (LearningGp) [reply sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/ConsoleHandler.java]: Looks cool! FYR, we may not need to print full content though System.err. As prompting once when the log is discarded for the first time in a certain period of time may be enough to avoid misleading. BTW, the label of sentinel when print through System.err should be needed, in order to let the user know that the output comes from Sentinel.

Comment (karl-sy) [reply sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/ConsoleHandler.java]: has add sentinel tag to identify the record log is printed by sentinel SDK.

Comment (LearningGp) [reply sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/jul/ConsoleHandler.java]: LGTM

**Review by sczyh30 — COMMENTED** [review]
The test cases could be improved later.

**Review by sczyh30 — APPROVED** [review]
LGTM

**Comment by sczyh30** [comment]
Thanks for contributing!
