### PR TITLE
[ISSUE #943]Fix Console add rules Chinese garbled

### LINKED ISSUE #943: Console add rules Chinese garbled Console add rules Chinese garbled
## Issue Description
控制台添加规则中文乱码
Console add rules Chinese garbled

### Describe what happened (or what feature you want)
从控制台添加修改规则传到客户端的规则乱码
Adding a modification rule from the console to the client's rules garbled

### Describe what you expected to happen
期望可以兼容中文，在控制台流量监控时可以用中文来描述服务名
Expect to be compatible with Chinese. In console traffic monitoring, you can use Chinese to describe the service name.

### How to reproduce it (as minimally and precisely as possible)

1. 控制台添加中文规则名就可重现
1. The console can be reproduced by adding the Chinese rule name.

### Tell us your environment
windows和liunx皆是如此
Both windows and liunx are like this

### Anything else we need to know?
我在分支已经提交编码设置，是否还需要改动请看一下
版本号：d4df668300799ea6f19e12352769275eca4890ae

I have already submitted the encoding settings in the branch. Do you still need to change it? Please take a look.
Version number: d4df668300799ea6f19e12352769275eca4890ae

### PR DESCRIPTION
**Pull request by zhenxianyimeng**
### Describe what this PR does / why we need it
support Chinese rules in sentinel console

### Does this pull request fix one issue?
Fixes #943

### Describe how you did it
change UrlEncodedFormEntity with utf-8

The client will get: content-type: application/x-www-form-urlencoded; charset=utf-8

change the judge equals to "application/x-www-form-urlencoded"

### Describe how to verify it
sentinel-demo-spring-webmvc as a client
run client and console, add chinese rules

### CODE REVIEW

File: sentinel-transport/sentinel-transport-simple-http/src/main/java/com/alibaba/csp/sentinel/transport/command/http/HttpEventTask.java [hunk 1]
```diff
@@ -113,6 +113,10 @@ public void run() {
                     String headerName = bodyLine.substring(0, index);
                     String header = bodyLine.substring(index + 1).trim();
                     if (StringUtil.equalsIgnoreCase("content-type", headerName)) {
+                        int idx = header.indexOf(";");
+                        if(idx > 0){
+                            header = header.substring(0,idx).trim();
+                        }
```
Comment (sczyh30) [inline sentinel-transport/sentinel-transport-simple-http/src/main/java/com/alibaba/csp/sentinel/transport/command/http/HttpEventTask.java]: Could you please reformat your code here?

**Comment by sczyh30** [comment]
Thanks for contributing!
