### PR TITLE
Fix NPE in Tracer when context size exceeds the limit (#1184)

### LINKED ISSUE #1184: Tracer.trace(ex) NPE in Context.getCurNode when context size exceeds the limit
## Issue Description

Type: bug report
java.lang.NullPointerException: null\n\tat com.alibaba.csp.sentinel.context.Context.getCurNode(Context.java:112) ~[sentinel-core-1.4.0.jar!/:1.4.0]\n\tat com.alibaba.csp.sentinel.Tracer.trace(Tracer.java:45) ~[sentinel-core-1.4.0.jar!/:1.4.0]\n\tat com.alibaba.csp.sentinel.Tracer.trace(Tracer.java:32)

### Tell us your environment
spring boot 2.0.0.RELEASE, sentinel  0.2.1.RELEASE

### PR DESCRIPTION
**Pull request by cdfive**
### Describe what this PR does / why we need it

When context size exceeds the limit, `Tracer#trace` throws NPE.

### Does this pull request fix one issue?

Fixes #1184

### Describe how you did it

Add checking logic in `Tracer#traceContext` and `Context#getCurNode`.

### Describe how to verify it

Add a test case `TracerTest#testTraceWhenContextSizeExceedsThreshold`.

### Special notes for reviews

`Tracer#trace(Throwable, int)` do a small improvements, 
call `Tracer#traceContext(Throwable, int, Context)` to avoid duplicate code.

### CODE REVIEW

File: sentinel-core/src/test/java/com/alibaba/csp/sentinel/TracerTest.java [hunk 1]
```diff
@@ -8,6 +9,24 @@
...
+        }
+
+        try {
+            ContextUtil.enter("test-context-" + i);
+            throw new RuntimeException("test");
+        } catch (Exception e) {
+            Tracer.trace(e);
+        } finally {
+            ContextUtil.exit();
+        }
```
Comment (sczyh30) [inline sentinel-core/src/test/java/com/alibaba/csp/sentinel/TracerTest.java]: Maybe we need to do some context clean-up here (using [ContextTestUtil](https://github.com/alibaba/Sentinel/blob/master/sentinel-core/src/test/java/com/alibaba/csp/sentinel/context/ContextTestUtil.java))?

Comment (cdfive) [reply sentinel-core/src/test/java/com/alibaba/csp/sentinel/TracerTest.java]: Yes, it's needed. Very precise!

**Comment by sczyh30** [comment]
Thanks!
