### PR TITLE
fix the potential concurrence issue when rules updates

### LINKED ISSUE #1782: Potential concurrence issue happens when updating rules
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
When you update rules, XXXRuleManager.XXXPropertyListener.configUpdate will be called, and it's not atomic action of calling clear() and putAll(). That could make it no rule in an instant.

### Describe what you expected to happen
Whenever you call XXXRuleManager.getRules(), the rules should be initial ones or the updated ones, there should never be empty.

### How to reproduce it (as minimally and precisely as possible)

1. create a UT class for FlowRuleManager which contains a loader thread which is loading FlowRules again and again.
2. in the man thread, just do getRules again and again.
3. if the size happens to 0, there must be the issue.

### Tell us your environment
None of env's business

### Anything else we need to know?
I'll submit a UT later to prove it

### PR DESCRIPTION
**Pull request by vipweihua**
### Describe what this PR does / why we need it
fix the potential concurrence issue when rules updates

### Does this pull request fix one issue?
Fixes #1782.

### Describe how you did it
make the map wrapped in AtomicReference

### Describe how to verify it
Run the new-added UT 

### Special notes for reviews
If this pr can be acceptable, I plan to fix the same issue in other rule managers. 
Code seems to be strange in DegradeRuleManager because the same piece of code uses synchronized keyword. It seems to be realized, but in the wrong way to fix it.

### CODE REVIEW

File: sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/FlowRuleManager.java [hunk 1]
```diff
@@ -129,20 +130,16 @@ public static boolean isOtherOrigin(String origin, String resourceName) {
...
         public void configUpdate(List<FlowRule> value) {
             Map<String, List<FlowRule>> rules = FlowRuleUtil.buildFlowRuleMap(value);
-            if (rules != null) {
-                flowRules.clear();
-                flowRules.putAll(rules);
-            }
+            //the rules was always not null, it's no need to check nullable
+            //remove checking to avoid IDE warning
+            flowRules.set(rules);
             RecordLog.info("[FlowRuleManager] Flow rules received: {}", flowRules);
```
Comment (jasonjoo2010) [inline sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/FlowRuleManager.java:136]: Maybe the variable in logging message should be updated now.

**Review by jasonjoo2010 — CHANGES_REQUESTED** [review]

File: sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/FlowRuleManager.java (hunk 1 above)
Comment (vipweihua) [reply sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/FlowRuleManager.java]: fixed

**Comment by vipweihua** [comment]
@jasonjoo2010

File: sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/FlowRuleManager.java [hunk 2]
```diff
@@ -83,7 +85,7 @@ public static void register2Property(SentinelProperty<List<FlowRule>> property)
      */
     public static List<FlowRule> getRules() {
         List<FlowRule> rules = new ArrayList<FlowRule>();
-        for (Map.Entry<String, List<FlowRule>> entry : flowRules.entrySet()) {
+        for (Map.Entry<String, List<FlowRule>> entry : flowRules.get().entrySet()) {
```
Comment (jasonjoo2010) [inline sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/FlowRuleManager.java:88]: Is it necessary to initial its value (flowRules) to be an empty map obviously?
It's tricky now because the initial empty value is initialized by `currentProperty.addListener(LISTENER);` in static block. It may trigger a bug if anyone change any of them in future.

File: sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/FlowRuleManager.java [hunk 3]
```diff
@@ -129,21 +131,17 @@ public static boolean isOtherOrigin(String origin, String resourceName) {
...
             Map<String, List<FlowRule>> rules = FlowRuleUtil.buildFlowRuleMap(value);
-            if (rules != null) {
-                flowRules.clear();
-                flowRules.putAll(rules);
-            }
-            RecordLog.info("[FlowRuleManager] Flow rules received: {}", flowRules);
+            //the rules was always not null, it's no need to check nullable
+            //remove checking to avoid IDE warning
+            flowRules.set(rules);
+            RecordLog.info("[FlowRuleManager] Flow rules received: {}", flowRules.get());
```
Comment (jasonjoo2010) [inline sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/FlowRuleManager.java:137]: For eventual consistency maybe `rules` is better. Because there may be duplicated logs with same content when races occurred.

**Review by jasonjoo2010 — CHANGES_REQUESTED** [review]
Hi, wei

I have dropped new comments which I missed first and please have a look when you had time.

File: sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/FlowRuleManager.java (hunk 2 above)
Comment (vipweihua) [reply sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/FlowRuleManager.java:88]: Totally agree.

File: sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/FlowRuleManager.java (hunk 3 above)
Comment (vipweihua) [reply sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/FlowRuleManager.java:137]: Agree.

**Review by jasonjoo2010 — CHANGES_REQUESTED** [review]
LGTM

**Review by jasonjoo2010 — APPROVED** [review]
LGTM

**Comment by jasonjoo2010** [comment]
Thanks for contributing!
